name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RP_ENDPOINT: ${{ secrets.RP_ENDPOINT }}
      RP_UUID: ${{ secrets.RP_UUID }}
      RP_PROJECT: ${{ secrets.RP_PROJECT }}
      RP_LAUNCH: "CI_Run_${{ github.run_id }}"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests (parallel + retries)
        run: |
          pytest -n auto --reportportal --reruns 2 --reruns-delay 2 -q
