name: Run Automation Tests - Staging

on:
  workflow_run:
    workflows: [ "Run Automation Tests - QA" ]
    types:
      - completed

jobs:
  test:
    # Only run if the QA workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env: [ staging ]
        browser: [ chrome ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install chromedriver-autoinstaller

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run tests (UI + API)
        run: |
          chmod +x run_tests.sh
          python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"
          ./run_tests.sh ${{ matrix.env }} ${{ matrix.browser }} --headless

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report-${{ matrix.env }}-${{ matrix.browser }}
          path: reports/
