name: Run Automation Tests - QA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env: [ qa ]
        browser: [ chrome ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install chromedriver-autoinstaller

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run tests (UI + API)
        run: |
          chmod +x run_tests.sh
          python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"
          ./run_tests.sh ${{ matrix.env }} ${{ matrix.browser }} --headless

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
